[workspace]
members = [
    "src/day1",
    "src/day2",
    "src/day3"
]
default-members = ["src/day3"]

[workspace.package]
version = "0.1.0"
authors = ["ChromaMaster"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
